### ISSUE TITLE
Updated VSCode: Not working

### ISSUE THREAD

**Issue by ralequi** [ajshort/vscode-latex-preview#14] opened 2017-02-07 11:42 UTC
I just updated my visual studio code, and the plugin has stop working.
I press open preview, a new tab is open, but a black one. No error message, no feedback, nothing, just a black tab.

SO: Linux
VSCode: 1.9.0

**Comment by ajshort** [comment] 2017-02-07 11:44
Duplicate of #12

**Closed as completed by ajshort** 2017-02-07 11:44 UTC
